import type { Vec3 } from '../math/vec3.js'
import { vec3, VEC3_ZERO } from '../math/vec3.js'
import type { Quat } from '../math/quat.js'
import { QUAT_IDENTITY } from '../math/quat.js'
import type { Body3D, Body3DOptions } from './types.js'
import type { SceneNode } from '../scene/index.js'

/**
 * Internal per-body accumulators.
 * Using WeakMap keeps the public Body3D interface clean.
 */
const forceAccumulators3D = new WeakMap<Body3D, Vec3>()
const torqueAccumulators = new WeakMap<Body3D, Vec3>()

/**
 * Creates a 3D physics body with full linear and angular dynamics.
 *
 * @example
 * const cube = createBody3D({ mass: 2, inertiaTensor: 0.5 })
 * applyTorque3D(cube, vec3(0, 1, 0)) // spin around Y
 */
export function createBody3D(options?: Body3DOptions): Body3D {
  const mass = options?.mass ?? 1
  const isKinematic = options?.isKinematic ?? false
  const inverseMass = isKinematic || mass === 0 ? 0 : 1 / mass

  const inertia = options?.inertiaTensor ?? 1
  const inverseInertia = isKinematic || inertia === 0 ? 0 : 1 / inertia

  let position = options?.position?.clone() ?? vec3(0, 0, 0)
  let velocity = options?.velocity?.clone() ?? vec3(0, 0, 0)
  let orientation = options?.orientation?.clone() ?? QUAT_IDENTITY.clone()
  let angularVelocity = options?.angularVelocity?.clone() ?? VEC3_ZERO.clone()

  const body: Body3D = {
    get position(): Vec3 { return position },
    set position(v: Vec3) { position = v },
    get velocity(): Vec3 { return velocity },
    set velocity(v: Vec3) { velocity = v },
    get orientation(): Quat { return orientation },
    set orientation(q: Quat) { orientation = q },
    get angularVelocity(): Vec3 { return angularVelocity },
    set angularVelocity(v: Vec3) { angularVelocity = v },
    mass,
    inverseMass,
    inverseInertia,
    damping: options?.damping ?? 1,
    angularDamping: options?.angularDamping ?? 0.99,
    isKinematic,
  }

  forceAccumulators3D.set(body, vec3(0, 0, 0))
  torqueAccumulators.set(body, vec3(0, 0, 0))
  return body
}

/**
 * Retrieves the current linear force accumulator for a body.
 *
 * @internal
 */
export function getForce3D(body: Body3D): Vec3 {
  return forceAccumulators3D.get(body) ?? vec3(0, 0, 0)
}

/**
 * Retrieves the current torque accumulator for a body.
 *
 * @internal
 */
export function getTorque3D(body: Body3D): Vec3 {
  return torqueAccumulators.get(body) ?? vec3(0, 0, 0)
}

/**
 * Resets both accumulators to zero after each integration step.
 *
 * @internal
 */
export function resetAccumulators3D(body: Body3D): void {
  forceAccumulators3D.set(body, vec3(0, 0, 0))
  torqueAccumulators.set(body, vec3(0, 0, 0))
}

/**
 * Accumulates a linear force on a body (applied during next `world.step()`).
 *
 * When `worldPoint` is provided, also applies the torque generated by the
 * off-centre force: `torque += (worldPoint - position) × force`.
 *
 * @example
 * applyForce3D(body, vec3(10, 0, 0))                         // linear push
 * applyForce3D(body, vec3(0, 5, 0), body.position.add(vec3(1, 0, 0))) // push + torque
 */
export function applyForce3D(body: Body3D, force: Vec3, worldPoint?: Vec3): void {
  const currentForce = forceAccumulators3D.get(body) ?? vec3(0, 0, 0)
  forceAccumulators3D.set(body, currentForce.add(force))

  if (worldPoint !== undefined) {
    const r = worldPoint.sub(body.position)
    const currentTorque = torqueAccumulators.get(body) ?? vec3(0, 0, 0)
    torqueAccumulators.set(body, currentTorque.add(r.cross(force)))
  }
}

/**
 * Accumulates a direct torque on a body (applied during next `world.step()`).
 *
 * @example
 * applyTorque3D(body, vec3(0, 2, 0)) // spin around Y-axis
 */
export function applyTorque3D(body: Body3D, torque: Vec3): void {
  const current = torqueAccumulators.get(body) ?? vec3(0, 0, 0)
  torqueAccumulators.set(body, current.add(torque))
}

/**
 * Applies an instant velocity change.
 * When `worldPoint` is provided, also applies the angular impulse from the lever arm.
 *
 * @example
 * applyImpulse3D(body, vec3(0, 5, 0)) // vertical kick
 */
export function applyImpulse3D(body: Body3D, impulse: Vec3, worldPoint?: Vec3): void {
  if (body.isKinematic) return
  body.velocity = body.velocity.add(impulse.scale(body.inverseMass))

  if (worldPoint !== undefined) {
    const r = worldPoint.sub(body.position)
    const angularImpulse = r.cross(impulse).scale(body.inverseInertia)
    body.angularVelocity = body.angularVelocity.add(angularImpulse)
  }
}

/**
 * Copies the body's position and orientation into a scene node.
 * Orientation is converted from quaternion to Euler angles (YXZ) for `node.rotation`.
 *
 * Note: Euler angles suffer from gimbal lock. For high-fidelity rendering,
 * prefer uploading `body.orientation.toMat4()` directly to your shader uniform.
 *
 * @example
 * syncBody3DToNode(cube, cubeNode)
 * updateBuffer(device, modelBuffer, cubeNode.worldMatrix().toFloat32Array())
 */
export function syncBody3DToNode(body: Body3D, node: SceneNode): void {
  node.position = body.position
  node.rotation = body.orientation.toEuler()
}
